server:
  port: 8081

# These are the default settings
graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true

# These are the default settings
# GraphiQL is available under http://localhost:8081/graphiql
graphiql:
  mapping: graphiql
  endpoint: /graphql
  enabled: true
  pageTitle: GraphiQL
  cdn:
    enabled: false
    version: 0.11.11
